### ISSUE TITLE
dynamic_compile should be in included_applications

### ISSUE THREAD

**Issue by silviucpp** [AdRoll/mero#21]
Hello,

dynamic_compile should be in included_applications not in applications config . 

Silviu

**Comment by miriampena** [comment]
Hi Silviu! Thanks for your contributions and comments! 
An included application is an application that has its own application directory and .app file, but it is started as part of the supervisor tree of another application.
In this case dynamic_compile is not an application, it does not have .app file, it just a library but what is more important is that it is not started in the supervision tree of mero. ( Example: mero_sup does not add a supervisor/gen_server belonging to the dynamic_compile application to its supervision tree). It does have a dependency on it since it needs to be loaded in order for mero to use it, and that is why it is marked as a dependency application.
Let me know if you have further questions.

**Comment by silviucpp** [comment]
Hello, 

Thanks for clarification, I thought that all deps that are libraries without application behavior should be part of included_applications. 

Idea is that without this dep in included_applications my application is no longer starting when doing a rebar release. I will check why right now I have no clue

Silviu
